# Generated by Django 4.2.3 on 2023-07-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_receipt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='title',
            new_name='restaurant',
        ),
    ]
