# Generated by Django 4.2.3 on 2023-07-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_title_receipt_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='restaurant',
            new_name='title',
        ),
    ]
