# Generated by Django 4.2.3 on 2023-07-31 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_date_receipt_datepick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(choices=[('P', 'Paid'), ('N', 'Not Paid Yet')], default=1, max_length=1)),
                ('date', models.DateField(verbose_name='When Was it Paid Off')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.receipt')),
            ],
        ),
    ]
