# Generated by Django 4.2.3 on 2023-08-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_people_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='people',
            field=models.ManyToManyField(to='main_app.people'),
        ),
    ]
